# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# Use latest Ubuntu image
pool:
  vmImage: 'ubuntu-latest'

# Pipeline
steps:
- checkout: none
- script:
      
# Install urlencode function to encode reserved characters in passwords
#sudo apt-get install gridsite-clients

# Create local mirror of Azure DevOps repository
git clone https://${AZPAT}:@https://dev.azure.com/BrainvireInfo/_git/IT-Project
git remote add --mirror=fetch secondary https://${GITPAT}:@github.com/github-dotnet/it-test.git
git fetch origin
git push secondary --all --force